# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afa87c38e20c13a30d35fa3c3d5784c5462f7c2538b81e1252bc5f4142dfa6ebaf2949d4a061a11f85e599e2b907e4d3af4550a325595e960ecf12486f58de13

test:
  secret_key_base: 5a916d73208f7c218c723046f19d84a9de7a4da66518b48763ba0c17eb6b665fb567019f1c93d06746a0c91cfdf97e3c3e52db3b6cbfa6695a091115b2643e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
